### ISSUE TITLE
Duplicated Properties

### ISSUE THREAD

**Issue by DanielBenesch** [spree-contrib/spree_i18n#597] opened 2015-07-01 20:52 UTC
To reproduce on 3-0-stable:

make a new rails project with spree and include & install spree i18n.
Log in as admin.

This is the properties list (if you loaded the sample data): 

![image](https://cloud.githubusercontent.com/assets/12606757/8463430/83b27900-203a-11e5-876a-bac3219962d4.png)

Then go to a product and update its properties (doesnt matter if you really change something, you can just click update if you want to):

![image](https://cloud.githubusercontent.com/assets/12606757/8463474/d25ac7a6-203a-11e5-82d6-23711a3069f3.png)

The properties panel should look the same, we didnt include new properties, but look: 

![image](https://cloud.githubusercontent.com/assets/12606757/8463518/2e831038-203b-11e5-9ec3-f3c0a22ab99a.png)

It adds the properties of the product you updated, no matter if the property already exists in the properties panel or not. So if you work with i18n you would have to update the translation for every property of every product. In addition you have no good overview about your properties. 

Whats interesting: If you look at the picture i have Manufactorer 2 times there in the list. But if I click in the search bar and filter, then it only finds 1.

I have absolutely no clue what is going on. 

# Important note:

I recognized this issue when I had a few additional gems installed. So i made a completly new project. The error does not appear in the normal spree app! It just happens after installing spree i18n.

**Comment by istickz** [comment] 2015-07-13 16:36
+1, I have the same problem

**Comment by alepore** [comment] 2015-07-14 16:16
Are properties actually duplicated on the database or it's just the same link repeated more times?

**Comment by istickz** [comment] 2015-07-16 06:37
Yes, properties duplicated on database.

**Comment by ijohn** [comment] 2015-07-19 07:10
My experience is different from @DanielBenesch 
I just did the following:

```
$ uname -a
Darwin Johns-MacBook-Air.local 15.0.0 Darwin Kernel Version 15.0.0: Sun Jun 28 00:25:56 PDT 2015; root:xnu-3247.1.36~7/RELEASE_X86_64 x86_64
$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin15]
$ rails _4.2.3_ new mystore
```

Before we continue, comment out `gem 'spring'` line in `Gemfile` because if not, `spree install` will hang (at least in my machine).

```
$ cd mystore
$ spree -v
3.0.1
$ spree install --auto-accept
```

Add `gem 'spree_i18n', github: 'spree-contrib/spree_i18n', branch: '3-0-stable'` to the end of `Gemfile`

````
$ bundle
$ rails g spree_i18n:install
$ rails s
````

- Go to http://localhost:3000/ -> Fine
- Go to http://localhost:3000/admin login as `spree@example.com` with password `spree123`
- Find a product, change something, click on Update button
- Properties don't get duplicated

**Comment by ijohn** [comment] 2015-07-19 07:31
My bad. @DanielBenesch was right. Steps to reproduce:

- Go to http://localhost:3000/admin login as spree@example.com with password spree123
- Find a product, __go to its Properties__, click on Update button
- Properties __get duplicated__

If you redo the last 2 steps, properties will get duplicated again.

**Comment by ijohn** [comment] 2015-07-23 15:03
My partner and I (both new to Ruby and Rails), did some digging and found the following:

The insertion to table `spree_properties` happen because of the following SQL query:
````
SELECT  "spree_properties".* FROM "spree_properties"
INNER JOIN "spree_property_translations"
ON "spree_property_translations"."spree_property_id" = "spree_properties"."id"
WHERE
"spree_property_translations"."name" =
'--- !ruby/object:ActiveRecord::StatementCache::Substitute {}'
AND "spree_property_translations"."locale" IN ('en', 'id') LIMIT 1
````
The query above is the result of execution of `Property.find_by(name: name)` from this [line](https://github.com/spree/spree/blob/3-0-stable/core/app/models/spree/product_property.rb#L21). Since there is no result for the query above, the [next line](https://github.com/spree/spree/blob/3-0-stable/core/app/models/spree/product_property.rb#L22) gets executed: `property = Property.create(name: name, presentation: name)`.

Please take a look at the weird `'--- !ruby/object:ActiveRecord::StatementCache::Substitute {}'` string in the query above. I think this has something to do with [globalize/globalize#423](https://github.com/globalize/globalize/issues/423).

**Comment by alepore** [comment] 2015-08-19 08:23
indeed, the WHERE in this query doesn't look very good:

```sql
Spree::Property Load (0.5ms)
SELECT  "spree_properties".* FROM "spree_properties"
INNER JOIN "spree_property_translations"
ON "spree_property_translations"."spree_property_id" = "spree_properties"."id"
WHERE "spree_property_translations"."name" = '--- !ruby/object:ActiveRecord::StatementCache::Substitute {}'
AND "spree_property_translations"."locale" IN ('it', 'en')
LIMIT 1
```

**Comment by alepore** [comment] 2015-08-19 08:25
related to https://github.com/globalize/globalize/issues/423

**Comment by alepore** [comment] 2015-08-19 08:56
@ijohn your analysis is correct, i opened a spree PR to avoid the `find_by`

**Comment by ijohn** [comment] 2015-08-19 09:11
Thank you very much @alepore

**Comment by alepore** [comment] 2015-08-29 06:59
can someone confirm this is fixed with latest spree?

**Comment by ijohn** [comment] 2015-08-29 08:18
I have tested on both master and 3-0-stable and this problem is fixed

**Closed** 2015-08-29 08:27 UTC
