### ISSUE TITLE
search product with translation

### ISSUE THREAD

**Issue by wuboy0307** [spree-contrib/spree_i18n#592] opened 2015-06-14 21:40 UTC
admin products page use ransack gem to search.
spree_i18n use globalize to save translated columns to translation table.
However, if we just search name_cont, ransack only search product table without translation.
We have to modify controller and view to fix this.

1. Spree::Admin::ProductsController:
@search = @collection.ransack(params[:q]) 
 =>
@search = @collection.with_translations(I18n.locale).ransack(params[:q])

2. view/spree/admin/products/index.html.erb:
<%= f.text_field :name_cont, :size => 15, class: "form-control js-quick-search-target" %>
=>
<%= f.text_field :translations_name_cont, :size => 15, class: "form-control js-quick-search-target" %>

This will also happen in other search form use ransack.

Please refer to this article:
http://www.synbioz.com/blog/internationalization_with_globalize

**Comment by JDutil** [comment] 2015-06-15 18:48
This is duplicate of https://github.com/spree-contrib/spree_i18n/issues/530

**Closed by JDutil** 2015-06-15 18:48 UTC
