### ISSUE TITLE
ActiveRecord::RecordNotFound: Couldn't find Spree::Taxon

### ISSUE THREAD

**Issue by greendog** [spree-contrib/spree_i18n#524] opened 2015-03-05 17:31 UTC
1. ```rails new test_app```
2. add ```gem 'spree', :git => 'git://github.com/spree/spree.git', :branch => '3-0-stable'``` and ```gem 'spree_i18n', :git => 'git://github.com/spree/spree_i18n.git', :branch => '3-0-stable'``` to ```Gemfile```
3. ```rake db:migrate && rake db:seed```
4. ```bundle exec rake spree_sample:load``` <-- here i have an problem

Point of the error: https://github.com/spree/spree/blob/3-0-stable/sample/db/samples/taxons.rb#L142

If I remove ```spree_i18n```, then the error disappears.

If i do ```Spree::Taxon.find_by_name('Brand')```

i see:

```Spree::Taxon Load (1.2ms)  SELECT  `spree_taxons`.* FROM `spree_taxons` INNER JOIN `spree_taxon_translations` ON `spree_taxon_translations`.`spree_taxon_id` = `spree_taxons`.`id` WHERE `spree_taxon_translations`.`name` = '--- !ruby/object:ActiveRecord::StatementCache::Substitute {}\n' AND `spree_taxon_translations`.`locale` = 'ru' LIMIT 1```

**Comment by JDutil** [comment] 2015-03-05 17:56
Did you do:
bundle exec rake railties:install:migrations

Before:
bundle exec rake db:migrate

**Comment by greendog** [comment] 2015-03-05 18:00
Yes of course.
I see these migration https://github.com/spree-contrib/spree_i18n/tree/master/db/migrate

**Comment by JDutil** [comment] 2015-03-05 18:07
Oh sorry you can't use the dynamic find_by helpers anymore with globalize this is a duplicate of:
https://github.com/spree-contrib/spree_i18n/issues/509

You need to use arel where queries because the info is stored in the taxon translations table not the taxons table.

**Closed by JDutil** 2015-03-05 18:07 UTC

**Comment by greendog** [comment] 2015-03-05 18:43
Fix is here: https://github.com/spree/spree/pull/6120
